In [ ]:
# numpy is a python library related to arry
# first import the numpy from library
# numpy array creation
# 1 arrange function
# arange(start, end, step(not mendatory))

In [ ]:
import numpy as np

arr = np.arange(1,11)
print(arr)

In [ ]:
# 2. using array
lst = [1,2,3,4,5,6,7]
arr = np.array(lst)
print(arr)
print(arr.dtype)

In [ ]:
lst = [1,2,3,4,5,6,7.7]
arr = np.array(lst)
print(arr)
print(arr.dtype)

In [ ]:
# control data type
lst = [1,2,3,4,5,6,7.7]
arr = np.array(lst,int)
print(arr)
print(arr.dtype)

In [ ]:
# 3. using linspace()  divide by default 50 part
arr = np.linspace(0,15)
print(arr)

In [ ]:
arr = np.linspace(0,15,25)
print(arr)

In [ ]:
#4 using logspace
arr = np.logspace(5,15,5)
print(arr)

In [ ]:
print(arr[1])

In [ ]:
print("%.2f"%arr[1])

In [ ]:
arr = np.zeros(5)
print(arr)

In [ ]:
arr = np.ones(6)
print(arr)

In [ ]:
arr = np.zeros(5,int)
print(arr)

In [ ]:
arr = np.ones((5,4))
print(arr)

In [ ]:
arr = np.ones((3,6),int)
print(arr)

In [ ]:
# numpy arr from list
list1 = [11,22,33,4,5,6,7]
print(type(list1))
arr = np.array(list1)
print(arr)
print(type(arr))

In [ ]:
list2 = [[1,2,3,4,5],[6,7,8,9,10]]
arr = np.array(list2)
print(arr)

In [ ]:
arr = np.full(7,7)
print(arr)

In [ ]:
arr = np.full((3,4),5)
print(arr)

In [4]:
import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
#Random generaton of Numpy.
arr = np.random.rand(5)
print(arr)

[0.8673252  0.59134241 0.23831114 0.1189916  0.4135598 ]


In [6]:
arr = np.random.rand(5,4)
print(arr)

[[0.01876146 0.72828482 0.4521306  0.44800365]
 [0.42576933 0.62887367 0.57843808 0.60699434]
 [0.88445804 0.92383793 0.10847998 0.92143525]
 [0.93819589 0.09317089 0.28920969 0.74469349]
 [0.77263748 0.89254759 0.69074181 0.70934625]]


In [7]:
arr = np.random.randint(0,11,10)
print(arr)

[1 6 7 9 3 4 4 6 9 5]


In [10]:
import numpy as np
arr1 = arr.reshape(4,5)
print(arr1)

ValueError: cannot reshape array of size 10 into shape (4,5)

In [11]:
m = arr.max()
print(m)

9


In [12]:
m = arr.min()
print(m)

1


In [13]:
print(arr.shape)


(10,)


In [14]:
print(arr.ndim)

1


In [15]:
print(arr.size)

10


In [16]:
print(arr.dtype)

int32


In [17]:
print(arr.itemsize)

4


In [18]:
print(arr.data)

In [19]:
arr = np.random.randint(0,100,10)
print(arr)

[41 55 52 95 61 75 52 10 63 16]


In [20]:
print(arr[3])

95


In [21]:
for i in arr:
    print(i,end=" ")

41 55 52 95 61 75 52 10 63 16 

In [23]:
row = 2
col = 3
mat =[]
for i in range(row):
    for j in range(col):
        data = int(input())
        mat.append(data)
print(mat)


6
5
4
3
2
1
[6, 5, 4, 3, 2, 1]


In [24]:
row  = 2
col = 3
mat = []
for i in range(row):
    mat.append([0]*col)
print(mat)

[[0, 0, 0], [0, 0, 0]]


In [25]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
print(arr+arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [30]:
arr1 = np.arange(5,15)
print(arr1)

[ 5  6  7  8  9 10 11 12 13 14]


In [31]:
print(arr+arr1)

[ 6  8 10 12 14 16 18 20 22 24]
