In [1]:
import numpy as np

my_list = [10,20,30,40,50]
arr = np.array(my_list)

print("array:",arr)
print("size:",arr.size)
print("datatype:",arr.dtype)
print("dimension:",arr.ndim)
print("shape:",arr.shape)

array: [10 20 30 40 50]
size: 5
datatype: int32
dimension: 1
shape: (5,)


In [2]:
my_list = [10,20,30],[40,50,60],[70,80,90]
matrix = np.array(my_list)

print(matrix)

print("size:",matrix.size)
print("datatype:",matrix.dtype)
print("dimension:",matrix.ndim)
print("shape:",matrix.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
size: 9
datatype: int32
dimension: 2
shape: (3, 3)


In [3]:
my_list = [10,20,30,40,50]
arr = np.array(my_list)
print("elements:")
for ele in arr:
    print(ele)
    


elements:
10
20
30
40
50


In [4]:
my_list = [10,20,30,],[40,50,60],[70,80,90]
matrix = np.array(my_list)
print("elements:")
print(matrix)

elements:
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
for row in matrix:
    for ele in row:
        print(ele,end=" ")
    print()

10 20 30 
40 50 60 
70 80 90 


In [6]:
for row in matrix:
    print(row)

[10 20 30]
[40 50 60]
[70 80 90]


In [7]:
my_list = [10,20,30,],[40,50,60],[70,80,90]
matrix = np.array(my_list)
res = matrix[ : , : ]
print(res)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [8]:
res = matrix[0:3,0:3]
print(res)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [9]:
# creating one dimensional array
import numpy as np
n = int(input("enter size:"))
arr = np.ndarray(shape=(n),dtype= int)
print("enter %d elements:" %n)
for i in range(n):
    arr[i] = int(input())
print("array elements:", arr)

enter size:3
enter 3 elements:
4
4
5
array elements: [4 4 5]


In [12]:
# two dimensional array in numpy.
import numpy as np
m = int(input("enter row size:"))
n = int(input("enter colum size:"))
matrix = np.ndarray(shape = (m,n),dtype=int)
print("size:",matrix.size)
print("shape:",matrix.shape)
print("dimension",matrix.ndim)
for i in range(m,n):
    matrix[i] = int(input())
print("matrix elements:", matrix)


enter row size:2
enter colum size:2
size: 4
shape: (2, 2)
dimension 2
matrix elements: [[   21455102   549737277]
 [-1372415988  1137170526]]


In [16]:
row = 2
col = 3
mat = []
for i in range(row):
    mat.append([6]*col)
print(mat)

[[6, 6, 6], [6, 6, 6]]


In [18]:
# numpy.ndarray
arr = np.ndarray(shape = (5),dtype = int)
n = arr.size
print("enter %d elements:"%n)
for i in range(n):
    arr[i] = int(input())
print("elements:",arr)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)


enter 5 elements:
10
20
30
40
50
elements: [10 20 30 40 50]
size: 5
shape: (5,)
dimension: 1
data type: int32


In [22]:
m = int(input("Enter row size:"))
n = int(input("Enter column size:"))
matrix = np.ndarray(shape = (m,n),dtype = int)
print("enter %d elements of %d*%d matrix:"%(m*n,m,n))
for i in range(m):
    for j in range(n):
        matrix[i][j] = int(input())
print("%d*%d matrix is:"%(m,n))
print(matrix)

Enter row size:2
Enter column size:3
enter 6 elements of 2*3 matrix:
1
2
3
4
5
6
2*3 matrix is:
[[1 2 3]
 [4 5 6]]


In [25]:
# numpy defining multi dimensional array
arr = np.ndarray(shape = (3,3,3), dtype = int)
print("enter %d elements:"%arr.size)
print("size:",arr.size)
print("shape:",arr.shape)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)


enter 27 elements:
size: 27
shape: (3, 3, 3)
dimension: 3
data type: int32


In [28]:
arr = np.ndarray(shape = (3,3,3), dtype = int)
value = 1
x = arr.shape[0]
y = arr.shape[1]
z = arr.shape[2]
for i in range(x):
    for j in range(y):
        for k in range(z):
            arr[i][j][k] = value
            value+=1
print("array elements:")
print(arr)

array elements:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [34]:
# numpy reshape
my_list = [11,22,33,44,55,66,77,88]
arr = np.array(my_list)
print("array:",arr)
print("size:",arr.size)
print("dimension:",arr.ndim)
res = arr.reshape(2,2,2)
print(res)
print("dimension:",res.ndim)

array: [11 22 33 44 55 66 77 88]
size: 8
dimension: 1
[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
dimension: 3
